//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apple_Clone_Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string ProductID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CategoryID { get; set; }
        public string SupplierID { get; set; }
        public string Image { get; set; }
        public string ProductColorID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ProductColor ProductColor { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
